export type PreparationCategory =
  | "now"
  | "tickets"
  | "apps"
  | "health"
  | "packing"
  | "final";

export type PreparationTask = {
  id: string;
  title: string;
  timing: string;
  where: string;
  owner: string;
  category: PreparationCategory;
  priority?: "urgent" | "normal";
  href?: string;
};

export const preparationTasks: PreparationTask[] = [
  {
    id: "walking-shoes",
    title: "לקנות נעלי הליכה חדשות לכולם",
    timing: "עד 31.7",
    where: "חנות ריצה או טיולים מקומית; למדוד בערב עם הגרביים של הטיול",
    owner: "כל המשפחה",
    category: "now",
    priority: "urgent",
  },
  {
    id: "break-in-shoes",
    title: "לשבור את הנעליים בהדרגה ולבצע מבחן 8–10 ק״מ",
    timing: "מהשבוע הראשון ועד 31.8",
    where: "שלוש הליכות קצרות ואז יום הליכה משפחתי עם גרביים ותיקי יום",
    owner: "כל המשפחה",
    category: "health",
  },
  {
    id: "nintendo-lottery",
    title: "להיכנס להגרלת Nintendo Museum ל־15.10",
    timing: "עד 31.7 · 23:59 JST",
    where: "באתר הכרטיסים הרשמי של Nintendo Museum",
    owner: "מבוגר מוביל",
    category: "tickets",
    priority: "urgent",
    href: "https://museum-tickets.nintendo.com/en/calendar?lang=en",
  },
  {
    id: "lodging-registration",
    title: "להשלים רישום אורחים בטוקיו ובקיוטו ולשמור אישור",
    timing: "עכשיו",
    where: "טופס המארח + Airbnb chat; פרטי כניסה נשמרים בתיקייה פרטית",
    owner: "מבוגר מוביל",
    category: "now",
    priority: "urgent",
  },
  {
    id: "remaining-lodging",
    title: "לסגור לינה באוסקה ובבלוק האחרון בטוקיו",
    timing: "עכשיו",
    where: "פלטפורמת ההזמנה שנבחרה; עדיפות לאפשרות ביטול",
    owner: "ההורים",
    category: "now",
    priority: "urgent",
  },
  {
    id: "insurance",
    title: "לקנות או לאשר ביטוח נסיעות משפחתי",
    timing: "עכשיו",
    where: "אתר חברת הביטוח; לבדוק רפואה, שיבושים וביטול הזמנות",
    owner: "ההורים",
    category: "health",
  },
  {
    id: "passports",
    title: "לבדוק דרכונים ושמות בכל ההזמנות",
    timing: "עכשיו",
    where: "בבית מול רישומי חברת התעופה והכרטיסים",
    owner: "ההורים",
    category: "now",
  },
  {
    id: "teamlab-kawaii",
    title: "לקנות teamLab Planets ו־KAWAII MONSTER LAND",
    timing: "בהקדם",
    where: "רק באתרי האטרקציות הרשמיים; שעות שמתאימות למסלול",
    owner: "מבוגר מוביל",
    category: "tickets",
    priority: "urgent",
  },
  {
    id: "mundo-pixar-decision",
    title: "לקנות Mundo Pixar ל־4.10",
    timing: "עכשיו",
    where: "לכוון ל־11:45/12:00; כ־¥20,100 למשפחה + עמלות. Pixar מוגן ומקצרים את Gundam/הקניונים והשקיעה",
    owner: "מבוגר מוביל",
    category: "tickets",
    priority: "urgent",
    href: "https://t.pia.jp/en/pia/events/mundopixar",
  },
  {
    id: "usj",
    title: "לקנות USJ Studio Pass + Express מדויק",
    timing: "בהקדם",
    where: "באתר USJ הרשמי; המוצר חייב לציין את מתקני Nintendo הרצויים",
    owner: "הורים + הילדים בוחרים מתקנים",
    category: "tickets",
    priority: "urgent",
    href: "https://www.usj.co.jp/web/en/us/tickets",
  },
  {
    id: "pokepark",
    title: "לעקוב אחרי מלאי רשמי ל־PokéPark ולהחליט על DisneySea",
    timing: "מעקב שבועי; החלטה עד 15.9",
    where: "החנות הרשמית בלבד; בלי Fiverr, מתווך או ספסר",
    owner: "המשפחה",
    category: "tickets",
    href: "https://ticket-en.pokepark-kanto.co.jp/",
  },
  {
    id: "hibiki",
    title: "לקנות HIBIKI ל־12.10 בשעה 19:00",
    timing: "להתחיל לבדוק ב־12.8",
    where: "אתר הכרטיסים הרשמי של DRUM TAO Kyoto",
    owner: "מבוגר מוביל",
    category: "tickets",
    href: "https://drum-tao-kyoto.com/en/ticket/",
  },
  {
    id: "mizuekai",
    title: "לקנות Mizuekai ל־11.10 בשעה 13:00",
    timing: "מיד כששיטת המכירה מתפרסמת",
    where: "העמוד הרשמי של Miyagawacho",
    owner: "מבוגר מוביל",
    category: "tickets",
    href: "https://www.miyagawacho.jp/mizuekai/",
  },
  {
    id: "ghibli",
    title: "לקנות Ghibli Museum ל־8.10 בשעה 10:00",
    timing: "10.9 · 04:00 שעון ישראל",
    where: "עמוד הכרטיסים הרשמי; שני המבוגרים מוכנים בזמן הפתיחה",
    owner: "מבוגר מזמין + גיבוי",
    category: "tickets",
    href: "https://www.ghibli-museum.jp/en/tickets/",
  },
  {
    id: "pokemon-cafe",
    title: "להזמין Pokémon Café ל־16.10",
    timing: "כשכללי אוקטובר יתפרסמו",
    where: "חדשות בית הקפה הרשמי בלבד; אין עמלת הזמנה לגיטימית",
    owner: "מבוגר מוביל",
    category: "tickets",
    href: "https://www.pokemon-cafe.jp/en/cafe/news/",
  },
  {
    id: "neco",
    title: "להזמין Neco Republic ולוודא כלל כניסת ילדים",
    timing: "2–4 שבועות לפני",
    where: "הערוץ הרשמי של הסניף באוצ׳נומיזו; להביא גרביים אטומות",
    owner: "מבוגר מוביל",
    category: "tickets",
  },
  {
    id: "connectivity",
    title: "לבחור חבילת eSIM / SIM / נדידה לשני טלפונים עצמאיים",
    timing: "עד 20.8",
    where: "אתר הספק; לבדוק שהטלפונים פתוחים ותומכים, כיסוי, hotspot והפעלה; בלי קוד משפיען לא מאומת",
    owner: "ההורים",
    category: "apps",
  },
  {
    id: "payments",
    title: "להכין שני כרטיסי תשלום, PIN ותוכנית מזומן/IC",
    timing: "עד 20.8",
    where: "אפליקציות הבנק והארנק; לא להסתמך על אמצעי אחד",
    owner: "ההורים",
    category: "now",
  },
  {
    id: "medicines",
    title: "להשלים תרופות קבועות והעתקי מרשמים",
    timing: "עד 31.8",
    where: "רופא משפחה / בית מרקחת; אריזות מקוריות ובתיק היד",
    owner: "כל מטייל",
    category: "health",
  },
  {
    id: "luggage",
    title: "לאשר קבלת משלוחי מזוודות ופתרון ל־15.10",
    timing: "עד 15.9",
    where: "אישור כתוב מהמארחים / מלונות + פתרון לוקר או שילוח",
    owner: "ההורים",
    category: "packing",
  },
  {
    id: "essential-apps",
    title: "להתקין Google Maps, Translate, Safety Tips ואפליקציית חברת התעופה",
    timing: "עד 10.9",
    where: "App Store / Google Play; להפעיל התראות Safety Tips",
    owner: "כל הטלפונים הרלוונטיים",
    category: "apps",
    href: "https://www.jnto.go.jp/safety-tips/eng/app.html",
  },
  {
    id: "attraction-apps",
    title: "להתקין ולהתחבר ל־USJ, PokéPark ושירות הרכבות שנבחר",
    timing: "עד 10.9",
    where: "Wi-Fi ביתי; לבדוק סיסמה וכרטיסים בפועל",
    owner: "שני המבוגרים",
    category: "apps",
  },
  {
    id: "offline-maps",
    title: "להוריד מפות Tokyo, Kyoto ו־Osaka ויפנית אופליין",
    timing: "עד 10.9",
    where: "Google Maps + Google Translate",
    owner: "שני המבוגרים; תרגום גם אצל הילדים",
    category: "apps",
  },
  {
    id: "ticket-folder",
    title: "לשמור כל QR/PDF בתיקייה משותפת ובאופליין",
    timing: "מיד אחרי כל רכישה; בדיקה סופית 28.9",
    where: "ענן פרטי + עותק מקומי בשני טלפוני המבוגרים",
    owner: "מי שקונה",
    category: "apps",
  },
  {
    id: "wardrobe",
    title: "להכין לכל אחד מערכת שכבות קלה ועמידה לגשם",
    timing: "עד 29.9",
    where: "חולצה קלה + שכבה דקה + מכנס נוח + מעיל גשם מתקפל",
    owner: "כל המשפחה",
    category: "packing",
  },
  {
    id: "rain-kit",
    title: "לארוז מעיל גשם וערכת יום רטוב לכל אחד",
    timing: "עד 29.9",
    where: "תיקי היום; מטרייה קומפקטית לערים וגרביים חלופיים",
    owner: "כל המשפחה",
    category: "packing",
  },
  {
    id: "forecast",
    title: "לבדוק תחזית אמיתית והתראות גשם/טייפון",
    timing: "כל יום מ־24.9",
    where: "JMA + Safety Tips + הודעות חברת התעופה והרכבות",
    owner: "מבוגר מוביל",
    category: "final",
    priority: "urgent",
    href: "https://www.jma.go.jp/bosai/map.html#contents=forecast",
  },
  {
    id: "official-rechecks",
    title: "לבדוק סגירות, תחזוקה, מגבלות גיל/גובה ולוחות אירועים",
    timing: "24–28.9",
    where: "באתרים הרשמיים של כל אטרקציה ואירוע",
    owner: "ההורים",
    category: "final",
  },
  {
    id: "pokemon-projection-recheck",
    title: "לבדוק אם הקרנת Pokémon מופיעה בלוח 10.10",
    timing: "24.9–9.10",
    where: "לוח Tokyo Night & Light הרשמי בלבד; לבחור הקרנה מוקדמת ולהתעלם משעות האינסטגרם",
    owner: "מבוגר מוביל",
    category: "final",
    href: "https://tokyoprojectionmappingproject.jp/en/",
  },
  {
    id: "yuzen-recheck",
    title: "לאשר פתיחת Yūzen ב־13.10 ולהכין ארבעה איותים",
    timing: "24.9–9.10",
    where: "לוודא פתיחה ביום ג׳ ב־09:30, חריטה לפני הצ׳ק־אאוט ומחיר בפועל",
    owner: "מבוגר מוביל + כל המשפחה",
    category: "final",
    href: "https://page.line.me/xat.0000115429.mcu",
  },
  {
    id: "visit-japan-web",
    title: "להשלים Visit Japan Web אם בוחרים להשתמש בו",
    timing: "בשבוע האחרון",
    where: "רק באתר הרשמי; לשמור גם פרטי נסיעה כגיבוי",
    owner: "ההורים",
    category: "final",
    href: "https://www.vjw.digital.go.jp/",
  },
  {
    id: "narita",
    title: "לאשר טרמינל, רכבת לנריטה ושעת יציאה",
    timing: "29.9",
    where: "אפליקציית חברת התעופה + מתכנן הרכבות",
    owner: "ההורים",
    category: "final",
  },
  {
    id: "carry-on",
    title: "לארוז דרכונים, תרופות, מטענים ובגד החלפה בתיק היד",
    timing: "29–30.9",
    where: "בבית; הדברים הקריטיים לא נכנסים למזוודה שנשלחת",
    owner: "כל מטייל",
    category: "final",
  },
];

export const weatherCities = [
  { city: "טוקיו", high: "22.0°", low: "14.8°", rain: "234.8 מ״מ" },
  { city: "קיוטו", high: "23.4°", low: "14.4°", rain: "143.2 מ״מ" },
  { city: "אוסקה", high: "23.7°", low: "16.0°", rain: "136.0 מ״מ" },
];

export const categoryLabels: Record<PreparationCategory | "all", string> = {
  all: "הכול",
  now: "עכשיו",
  tickets: "כרטיסים",
  apps: "אפליקציות",
  health: "בריאות והליכה",
  packing: "ציוד ואריזה",
  final: "שבוע אחרון",
};
