export type TripDay = {
  day: number;
  date: string;
  shortDate: string;
  title: string;
  area: string;
  theme: string;
  image: string;
  color: string;
  lat: number;
  lng: number;
  highlights: string[];
  note?: string;
  discovery?: {
    label: string;
    title: string;
    detail: string;
    href: string;
  };
};

export const tripDays: TripDay[] = [
  {
    day: 1,
    date: "יום ה׳, 1 באוקטובר",
    shortDate: "1.10",
    title: "ממריאים ליפן",
    area: "תל אביב ← אדיס אבבה",
    theme: "יום טיסות",
    image: "/images/tokyo-sunset.jpg",
    color: "#d65a3a",
    lat: 8.9779,
    lng: 38.7993,
    highlights: ["ET419 בשעה 15:35", "קונקשן של 2:45 שעות", "ET672 לנריטה"],
  },
  {
    day: 2,
    date: "יום ו׳, 2 באוקטובר",
    shortDate: "2.10",
    title: "נוחתים בטוקיו",
    area: "נריטה ← טבטה",
    theme: "נחיתה והתארגנות",
    image: "/images/tokyo-sunset.jpg",
    color: "#1d6f74",
    lat: 35.7138,
    lng: 139.7773,
    highlights: ["נחיתה ב־19:40", "רכבת לטוקיו", "צ׳ק־אין מאוחר וקונביני"],
    note: "לא מתכננים אטרקציות בערב הזה.",
  },
  {
    day: 3,
    date: "שבת, 3 באוקטובר",
    shortDate: "3.10",
    title: "אקיהברה",
    area: "Electric Town ← אוצ׳נומיזו",
    theme: "אנימה, משחקים וחתולי הצלה",
    image: "/images/akihabara.jpg",
    color: "#8b5cf6",
    lat: 35.6984,
    lng: 139.7731,
    highlights: ["Radio Kaikan", "Mandarake אחרי 12:00", "HEY / GiGO / Super Potato", "Neco Republic"],
    note: "מגינים על זמן המשחק ועל הזמנת בית הקפה; קניות עם רשימה ותקציב.",
  },
  {
    day: 4,
    date: "יום א׳, 4 באוקטובר",
    shortDate: "4.10",
    title: "teamLab ואודאיבה",
    area: "טויוסו ← אודאיבה",
    theme: "אמנות בתוך מים, גונדאם וגיימינג",
    image: "/images/tokyo-sunset.jpg",
    color: "#28a7a1",
    lat: 35.6191,
    lng: 139.7764,
    highlights: ["teamLab Planets", "Unicorn Gundam", "Gundam Base", "Tokyo Joypolis"],
    note: "מדלגים על שיטוט בקניונים ושומרים 3–4 שעות למשחק אמיתי ב־Joypolis.",
    discovery: {
      label: "שדרוג אופציונלי · כ־¥20,100 למשפחה + עמלות",
      title: "Mundo Pixar נכנס בדיוק בין teamLab לאודאיבה",
      detail:
        "אם המשפחה בוחרת בו, מזמינים כניסה מתוזמנת סביב 11:45–12:00 ומקצרים את Gundam Base והשקיעה — או מחליפים חלק מ־Joypolis. לא דוחסים שלוש אטרקציות מלאות.",
      href: "https://t.pia.jp/en/pia/events/mundopixar",
    },
  },
  {
    day: 5,
    date: "יום ב׳, 5 באוקטובר",
    shortDate: "5.10",
    title: "PokePark Kanto",
    area: "Yomiuriland",
    theme: "יום פוקימון גדול",
    image: "/images/fuji.jpg",
    color: "#f2b134",
    lat: 35.6252,
    lng: 139.517,
    highlights: ["כניסה מתוזמנת", "Pokémon Forest", "Sedge Town", "מרצ׳נדייז 30 שנה"],
    note: "קונים רק דרך ערוץ רשמי או מורשה. אם אין כרטיסים רשמיים — DisneySea מחליף את היום; לא משתמשים ב־Fiverr או בספסר.",
  },
  {
    day: 6,
    date: "יום ג׳, 6 באוקטובר",
    shortDate: "6.10",
    title: "הרג׳וקו ושיבויה",
    area: "מערב טוקיו",
    theme: "קוואי, נינטנדו ופוקימון",
    image: "/images/shibuya.jpg",
    color: "#f05d7c",
    lat: 35.6595,
    lng: 139.7005,
    highlights: ["Meiji Jingu קצר", "KAWAII MONSTER LAND", "Nintendo TOKYO", "Pokémon Center Shibuya"],
    note: "Shibuya Sky הוא בונוס; קומת הפאנדום ב־PARCO היא העיקר.",
  },
  {
    day: 7,
    date: "יום ד׳, 7 באוקטובר",
    shortDate: "7.10",
    title: "קמקורה ואנושימה",
    area: "טיול חוף",
    theme: "בודהה ענק, Slam Dunk, רכבת וחוף",
    image: "/images/sensoji.jpg",
    color: "#6b8d5c",
    lat: 35.3192,
    lng: 139.5467,
    highlights: ["Great Buddha", "מערת Hasedera", "מעבר Slam Dunk", "אנושימה ושקיעה"],
    note: "מסלול חד־כיווני דרך פוג׳יסאווה; בלי מרתון מקדשים.",
  },
  {
    day: 8,
    date: "יום ה׳, 8 באוקטובר",
    shortDate: "8.10",
    title: "ג׳יבלי, נקאנו ושינג׳וקו",
    area: "מיטאקה ← קיצ׳יג׳וג׳י ← נקאנו ← שינג׳וקו",
    theme: "קסם אנימציה, ציד אוצרות וסיום ניאון",
    image: "/images/akihabara.jpg",
    color: "#7157a8",
    lat: 35.6962,
    lng: 139.5704,
    highlights: ["Ghibli Museum ב־10:00", "ארוחת צהריים בקיצ׳יג׳וג׳י", "Nakano Broadway קצר", "חתול 3D ו־Godzilla"],
    note: "namco TOKYO הוא בונוס בלבד; מגינים על ג׳יבלי ועל קצב רגוע.",
  },
  {
    day: 9,
    date: "יום ו׳, 9 באוקטובר",
    shortDate: "9.10",
    title: "טבע, טוטורו ופסטיבל קארי",
    area: "טודורוקי ← סטגאיה ← שימוקיטזאווה",
    theme: "שני פארקים, אוכל רחוב וקוואי",
    image: "/images/ramen.jpg",
    color: "#4f7f67",
    lat: 35.6616,
    lng: 139.668,
    highlights: ["ערוץ טודורוקי", "פחזניות טוטורו", "פיקניק קצר ב־Hanegi Park", "Shimokitazawa Curry Festival"],
    note: "בגשם כבד מדלגים על הפארקים ושומרים על איסוף הטוטורו ועל מסלול מנות הקארי המקורות.",
  },
  {
    day: 10,
    date: "שבת, 10 באוקטובר",
    shortDate: "10.10",
    title: "יום חגיגה משפחתי",
    area: "Tokyo Dome City",
    theme: "רכבות הרים, קריוקי וארוחת חגיגה",
    image: "/images/shibuya.jpg",
    color: "#b48a3c",
    lat: 35.6762,
    lng: 139.6503,
    highlights: ["בוקר רגוע ומתנה", "Thunder Dolphin", "Big-O קריוקי", "ארוחת חגיגה"],
    note: "נשארים באזור אחד ונותנים לבן לבחור את הפעילות הראשונה.",
    discovery: {
      label: "תוספת חינמית · לוח אוקטובר טרם ננעל",
      title: "Pokémon Card Game על בניין עיריית טוקיו",
      detail:
        "רק אם הלוח הרשמי מציג את Pokémon בערב 10.10: יוצאים מ־Tokyo Dome דרך Kasuga ל־Tochomae, בוחרים את ההקרנה המוקדמת ומזמינים ארוחת חגיגה במערב שינג׳וקו. לא מסתמכים על שעות האינסטגרם.",
      href: "https://tokyoprojectionmappingproject.jp/en/",
    },
  },
  {
    day: 11,
    date: "יום א׳, 11 באוקטובר",
    shortDate: "11.10",
    title: "קיוטו: מיזואקאי ואוואטה",
    area: "טוקיו ← קיוטו ← מיאגאווה־צ׳ו ← Awata ← פושימי",
    theme: "ריקוד גייקו ותהלוכת לילה מסורתית",
    image: "/images/sensoji.jpg",
    color: "#5b8f62",
    lat: 35.0035,
    lng: 135.7786,
    highlights: ["שינקנסן מוקדם", "Mizuekai ב־13:00", "ארוחה ומנוחה", "תהלוכת Awata מ־17:00"],
    note: "את התיקים משאירים בתחנת קיוטו עד אחרי התהלוכה; הצ׳ק־אין בפושימי מתחיל ב־15:00.",
  },
  {
    day: 12,
    date: "יום ב׳, 12 באוקטובר",
    shortDate: "12.10",
    title: "UZUMASA ו־DRUM TAO",
    area: "קיוטו: פושימי ← אוזומאסה ← Kyoto Avanti",
    theme: "סמוראים ונינג׳ות ביום, תופי טאיקו בלילה",
    image: "/images/ramen.jpg",
    color: "#d64d45",
    lat: 35.0168,
    lng: 135.7076,
    highlights: ["UZUMASA ב־10:00", "מופעי סמוראים ונינג׳ות", "מנוחה במלון", "HIBIKI ב־19:00"],
    note: "Mibu Kyogen הוא החלפה מקוצרת בלבד; לא דוחסים אותו למסלול המומלץ.",
  },
  {
    day: 13,
    date: "יום ג׳, 13 באוקטובר",
    shortDate: "13.10",
    title: "פושימי אינארי ואוסקה",
    area: "קיוטו ← Fushimi Inari ← Namba",
    theme: "שערי טוריאי, אנימה ודוטונבורי",
    image: "/images/akihabara.jpg",
    color: "#dc5b3e",
    lat: 35.0116,
    lng: 135.7681,
    highlights: ["שערי הטוריאי התחתונים", "חריטת מקלות אכילה", "Den Den Town קצר", "Dotonbori"],
    note: "המקדש מוקדם, Yūzen ב־09:30, וצ׳ק־אאוט עד 11:00; אם הבוקר מתעכב מקצרים קניות כפולות באוסקה.",
    discovery: {
      label: "מזכרת מתוכננת · 20–30 דקות",
      title: "מקלות אכילה עם שם ב־Yūzen Fushimi",
      detail:
        "החנות דקה מ־JR Inari ופותחת בדרך כלל ב־09:30. החריטה על זוגות מתאימים אורכת כחמש דקות לזוג; מכינים מראש איות מדויק ומאמתים שעות ומחיר. מחיר הפתיחה ¥1,100 מהפוסט לא אומת.",
      href: "https://page.line.me/xat.0000115429.mcu",
    },
  },
  {
    day: 14,
    date: "יום ד׳, 14 באוקטובר",
    shortDate: "14.10",
    title: "Super Nintendo World",
    area: "Universal Studios Japan",
    theme: "יום פארק מלא",
    image: "/images/shibuya.jpg",
    color: "#e94a4a",
    lat: 34.6654,
    lng: 135.4323,
    highlights: ["כניסה מוקדמת", "Mario Kart", "Donkey Kong", "Frieren / One Piece אם מתאים"],
    note: "קונים מוצר Express שמציין במפורש את מתקני נינטנדו הרצויים; השמות משתנים.",
  },
  {
    day: 15,
    date: "יום ה׳, 15 באוקטובר",
    shortDate: "15.10",
    title: "Nintendo Museum וטוקיו",
    area: "אוסקה ← אוג׳י ← טוקיו",
    theme: "עוד חוויית גיימינג גדולה בדרך חזרה",
    image: "/images/tokyo-sunset.jpg",
    color: "#1d7373",
    lat: 35.6812,
    lng: 139.7671,
    highlights: ["הגרלה עד 31.7", "Nintendo Museum", "דרכונים בתיק", "שינקנסן מקיוטו"],
    note: "אם לא זוכים — חוזרים מיד לתוכנית המנוחה והנסיעה הישירה לטוקיו.",
  },
  {
    day: 16,
    date: "יום ו׳, 16 באוקטובר",
    shortDate: "16.10",
    title: "Pokémon Café, תופים ואסאקוסה",
    area: "ניהונבאשי ← Taiko-kan ← סנסו־ג׳י",
    theme: "ארוחת פאנדום, תיפוף וסיום טוקיו קלאסי",
    image: "/images/ramen.jpg",
    color: "#f2b134",
    lat: 35.6812,
    lng: 139.7746,
    highlights: ["Pokémon Café", "Taiko-kan לפני 15:00", "זוג bachi ממיאמוטו", "Senso-ji בשעת בין ערביים"],
    note: "חותכים קודם את Character Street ואת Skytree; מגינים על המוזיאון, הבאצ׳י והמקדש.",
  },
  {
    day: 17,
    date: "שבת, 17 באוקטובר",
    shortDate: "17.10",
    title: "נפרדים מיפן",
    area: "טוקיו ← נריטה",
    theme: "בוקר רגוע וטיסה הביתה",
    image: "/images/tokyo-sunset.jpg",
    color: "#667085",
    lat: 35.772,
    lng: 140.3929,
    highlights: ["צ׳ק־אאוט", "ארוחה אחרונה", "הגעה מוקדמת לנריטה", "ET673 ב־20:40"],
  },
];

export const mapPlaces = tripDays
  .filter((item) => item.day > 1)
  .map(({ day, title, area, lat, lng, color, image }) => ({
    day,
    title,
    area,
    lat,
    lng,
    color,
    image,
  }));

export const bookingTasks = [
  {
    status: "urgent",
    date: "עד 31.7 · 23:59 JST",
    title: "הגרלת Nintendo Museum",
    detail: "להגיש ל־15.10 בבוקר או בצהריים; אם לא זוכים, חוזרים לטוקיו ישירות.",
  },
  {
    status: "next",
    date: "מעקב שוטף",
    title: "PokePark Kanto",
    detail: "עוקבים רק אחרי מלאי רשמי ל־5.10; עדכון 1.8 חל על כניסות מנובמבר ואינו מבטיח פתיחה לאוקטובר. DisneySea הוא הגיבוי, ולא קונים דרך Fiverr.",
  },
  {
    status: "next",
    date: "בהקדם",
    title: "USJ + Express מדויק",
    detail: "לסגור 14.10 עם מוצר שמציין במפורש את מתקני נינטנדו הרצויים.",
  },
  {
    status: "next",
    date: "בהקדם",
    title: "KAWAII MONSTER LAND + teamLab",
    detail: "לסגור כניסות מתוזמנות ל־4.10 ול־6.10 בשעות שמתאימות למסלול.",
  },
  {
    status: "next",
    date: "החלטה עד 10.8",
    title: "Mundo Pixar — כן או לא",
    detail: "כ־¥20,100 למשפחה + עמלות. אם מוסיפים ל־4.10, מקצרים במפורש את Gundam/Joypolis ולא מעמיסים הכול.",
  },
  {
    status: "urgent",
    date: "עכשיו",
    title: "לינה לארבעת הבלוקים",
    detail: "טוקיו 2–11.10, קיוטו 11–13.10, אוסקה 13–15.10, טוקיו 15–17.10.",
  },
  {
    status: "later",
    date: "10.9 · 04:00",
    title: "Ghibli Museum",
    detail: "מכירת אוקטובר נפתחת ב־10:00 לפי שעון יפן — להזמין ל־8.10.",
  },
  {
    status: "next",
    date: "כשייפתח",
    title: "Mizuekai + DRUM TAO",
    detail: "מיזואקאי 11.10 ב־13:00; HIBIKI ב־12.10 ב־19:00, מכירה חודשיים מראש.",
  },
  {
    status: "later",
    date: "מועד טרם פורסם",
    title: "Pokémon Café",
    detail: "לעקוב אחרי החדשות הרשמיות ולהזמין ל־16.10 כשהבלוק ייפתח.",
  },
];

export const guideImages: Record<string, string> = {
  overview: "/images/tokyo-sunset.jpg",
  flights: "/images/tokyo-sunset.jpg",
  stay: "/images/shibuya.jpg",
  transport: "/images/tokyo-sunset.jpg",
  anime: "/images/akihabara.jpg",
  food: "/images/ramen.jpg",
  daytrips: "/images/fuji.jpg",
  mitzvah: "/images/sensoji.jpg",
  tips: "/images/shibuya.jpg",
  itinerary: "/images/shibuya.jpg",
  budget: "/images/tokyo-sunset.jpg",
  checklist: "/images/fuji.jpg",
};
